### ISSUE TITLE
Missing a way to favourite a radio station

### ISSUE THREAD

**Issue by MaximMoinat** [radioxproject/radioxproject.github.io#5]
First of all: great app! Works like a charm and finds many radio stations.

All I am missing is how I can add a radio station to my favourites. If anyone can tell me how, I will definitely give this app a five star rating on the appstore :-).

**Comment by radioxproject** [comment]
Hello. Please use the version from the site.

https://radioxproject.github.io <https://radioxproject.github.io/>

**Comment by MaximMoinat** [comment]
Thanks. That indeed works! However, in this version I miss the very useful function to search for radio streams on the web (outside of the app). That is a great feature of the Appstore feature, which allowed me to find all the stations I could dream of. Do I now need to manually add the streams that are not provided in the app?

**Comment by radioxproject** [comment]
in a future version, I will return the ability to search on the Internet

**Comment by MaximMoinat** [comment]
Thanks a lot for your quick responses, much appreciated.
